### ISSUE TITLE
Hacktoberfest2021

### ISSUE THREAD

**Issue by Manasvi070902** [ISTE-VIT/Projects-Archive#1]
This hacktoberfest, contribute to open source!
Kindly follow the guidelines or else your PR will be marked as invalid.
First-timers are welcome!

**Comment by bineetNaidu** [comment]
hey, would u like me to work on this issue :smiley: . But it would be great if u lay out more info. Thanks

**Comment by Manasvi070902** [comment]
> hey, would u like me to work on this issue 😃 . But it would be great if u lay out more info. Thanks

Hi, Kindly refer to [Contribute.md](https://github.com/ISTE-VIT/Projects-Archive/blob/main/CONTRIBUTE.md) file

**Comment by BIDISHA-CHANDA** [comment]
@Manasvi070902 Hello,can i contribute to Hacktoberfest2021 repository?

**Comment by Manasvi070902** [comment]
> @Manasvi070902 Hello,can i contribute to Projects-Archieve repository?

Yes, refer to [Contribute.md](https://github.com/ISTE-VIT/Projects-Archive/blob/main/CONTRIBUTE.md) file for further details

**Comment by chhatrapalsinhzala7** [comment]
@Manasvi070902  hello mam, can i contribute to this repo  ??

i am beginner and want to contribute in open source...

**Comment by Manasvi070902** [comment]
> @Manasvi070902 hello mam, can i contribute to this repo ??
> 
> i am beginner and want to contribute in open source...

Yes, it's open to everyone.

**Comment by Manasvi070902** [comment]
> @Manasvi070902 I want to upload my app on your App-dev/java/ can I do that mam ??

Yes, inside the java folder, create a folder with your project name and add project files inside it

**Comment by chhatrapalsinhzala7** [comment]
@Manasvi070902  mam can you please tell me how to create folder under the App-dev/Java/

i am trying but was not able to create folder.

**Comment by Manasvi070902** [comment]
> @Manasvi070902 mam can you please tell me how to create folder under the App-dev/Java/
> 
> i am trying but was not able to create folder.

1) You can clone the repo to your local system and add folder under Java. Check out [Contribute.md](https://github.com/ISTE-VIT/Projects-Archive/blob/main/CONTRIBUTE.md)
2) If you are using "Upload files" method to commit on github, you need to open Java folder, click on Upload Files and drag complete folder into the box.

Hope this helps!

**Comment by PAARTH2608** [comment]
Can we put our projects or we need to contribute for the ones that are there in this repo??

**Comment by Manasvi070902** [comment]
> Can we put our projects or we need to contribute for the ones that are there in this repo??

Both are accepted
You can add new projects and enhance the existing ones.

**Comment by SiddyDevelops** [comment]
@Manasvi070902 Hello, I have generated a PR #59. Please review it. Thank you.

**Comment by Manasvi070902** [comment]
> @Manasvi070902 Hello, I have generated a PR #59. Please review it. Thank you.

Done, Thanks for contributing!

**Comment by Sidhved** [comment]
Hi, I intend to contribute to OpenCV sub folder from Machine Learning with a project the animates the input image.
Can you please assign an relevant issue to me under Hacktoberfest2021 or do I have to create a new issue for the same?
